[package]
name = "Qglif"
version = "0.1.0"
authors = ["Fredrick Brennan <copypaste@kittens.ph>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# For display
#skulpin = { git = "https://github.com/aclysma/skulpin", rev = "ca6da4ca64484f7854b8502b08a33cfd5bab98fc", features = ["skia_complete", "skulpin_winit"] }
skulpin = { path = "../skulpin", features = ["skia_complete", "skulpin_winit"] }
skulpin-plugin-imgui = { path = "../skulpin/skulpin-plugin-imgui" }
sdl2 = { version = ">=0.33", features = ["bundled", "static-link"] }
imgui-winit-support = "0.4.0"
gl = "0.14.0"
glium = "0.27.0"

# For choosing font for toolbox
font-kit = "0.10.0"

# For global state
lazy_static = "1.4.0"

# For argument parsing
clap = "2.33.3"
git-version = "0.3.4"

# For UI toggles
enum-iterator = "=0.6.0"

# Display backtraces
backtrace = "0.3.0"
colored = "2.0.0"

## Our crates
# parses .glif files and gives us a place to put arbitrary data
glifparser = { git = "https://github.com/mfeq/glifparser" }
#glifparser = { path = "../glifparser" } # for development
