[package]
name = "Qglif"
version = "0.1.0"
authors = ["Fredrick Brennan <copypaste@kittens.ph>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# For display
# We might need to vendorize these some day. See aclysma/skulpin#66:
# https://github.com/aclysma/skulpin/issues/66#issuecomment-689244118
skulpin = { version = "0.10.0", default-features = false, features = ["skia_complete", "skulpin_winit"] }
skulpin-plugin-imgui = "0.5.0"
imgui-winit-support = "0.4.0"

# For choosing font for toolbox
font-kit = "0.10.0"

# For global state
lazy_static = "1.4.0"

# For argument parsing
clap = "2.33.3"
git-version = "0.3.4"

# For UI toggles
enum-iterator = "=0.6.0"

# Display backtraces
backtrace = "0.3.0"
colored = "2.0.0"

# Logging
log = "0.4.11"
env_logger = "0.7.1"

## Our crates
# parses .glif files and gives us a place to put arbitrary data
glifparser = { git = "https://github.com/mfeq/glifparser" }
#glifparser = { path = "../glifparser" } # for development
mfeq-ipc = { git = "https://github.com/mfeq/ipc" }
