[package]
name = "MFEKglif"
version = "0.1.0"
authors = ["Fredrick Brennan <copypaste@kittens.ph>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# For display
# We might need to vendorize these some day. See aclysma/skulpin#66:
# https://github.com/aclysma/skulpin/issues/66#issuecomment-689244118
# Commented versions I occasionally use in development to stick extra debug!'s in Skulpin.
#skulpin = { version = "0.10.0", default-features = false, features = ["skia_complete", "skulpin_winit"] }
#skulpin = { path = "../skulpin", default-features = false, features = ["skia_complete", "skulpin_winit"] }
#skulpin-plugin-imgui = { path = "../skulpin/skulpin-plugin-imgui" }
skulpin = { version = "0.10.0", default-features = false, features = ["skia_complete", "skulpin_winit"] }
skulpin-plugin-imgui = { version = "0.5.0" }
imgui-winit-support = "0.4.0"

# For choosing font for toolbox
font-kit = "0.10.0"

# For global state
lazy_static = "1.4.0"

# For argument parsing
clap = "2.33.3"
git-version = "0.3.4"

# For UI toggles
enum-iterator = "=0.6.0"

# Display backtraces
backtrace = "0.3.53"
colored = "2.0.0"

# Right now only for pasting into console
clipboard = "0.5.0"

# Logging
log = "0.4.11"
env_logger = "0.7.1"

# Gives us derive(Display)
derive_more = "0.99.11"

# File dialog
nfd = { git = "https://github.com/raphlinus/nfd-rs", rev = "5e09b79bf511e3a91ae8cefdb96e9734fa4a79c2" }

# Command parsing for console
regex = "1"

## Our crates
# parses .glif files and gives us a place to put arbitrary data
glifparser = { git = "https://github.com/MatthewBlanchard/glifparser", branch = "variable-width-stroking"}

MFEKMath = {git = "https://github.com/MFEK/math"}

xmltree = "0.10.1"

#glifparser = { path = "../glifparser" } # for development
mfek-ipc = { git = "https://github.com/mfek/ipc" }

# See src/util/mod.rs::set_codepage_utf8
[target.'cfg(windows)'.dependencies]
winapi = "0.3"
