mod button;
pub use self::button::build as build_button;
pub use self::button::build_and_add as build_and_add_button;
pub use self::button::IntoResponse as IntoButtonResponse;

pub const KNIFE: &str = "\u{F000}";
pub const MEASURE: &str = "\u{F001}";
pub const PAN: &str = "\u{F002}";
pub const PEN: &str = "\u{F003}";
pub const _PENCIL: &str = "\u{F004}";
pub const SELECT: &str = "\u{F005}";
pub const SHAPES: &str = "\u{F006}";
pub const _TEXT: &str = "\u{F007}";
pub const ZOOM: &str = "\u{F008}";
pub const VWS: &str = "\u{F009}";
pub const ANCHOR: &str = "\u{F00A}";
pub const PAP: &str = "\u{F00B}";
pub const _OPENEYE: &str = "\u{F00C}";
pub const _CLOSEDEYE: &str = "\u{F00D}";
pub const _MINUS: &str = "\u{F00E}";
pub const _PLUS: &str = "\u{F00F}";
pub const _ARROWLEFT: &str = "\u{F010}";
pub const _ARROWDOWN: &str = "\u{F011}";
pub const _ARROWUP: &str = "\u{F012}";
pub const _ARROWRIGHT: &str = "\u{F014}";
pub const _RENAME: &str = "\u{F015}";
pub const _LAYERUNION: &str = "\u{F016}";
pub const _LAYERCOMBINE: &str = "\u{F017}";
pub const _LAYERDIFFERENCE: &str = "\u{F018}";
pub const _LAYERINTERSECTION: &str = "\u{F019}";
pub const _LAYERXOR: &str = "\u{F01A}";
pub const IMAGES: &str = "\u{F01C}";
pub const _GRID: &str = "\u{F029}";
pub const GUIDELINES: &str = "\u{F030}";
pub const HYPERBEZIER: &str = "\u{F031}";
pub const QUADRATIC: &str = "\u{F032}";
//pub const BSPLINE: &str = "\u{F033}";
//pub const SPIRO: &str = "\u{F034}";
pub const DASH: &str = "\u{F035}";
pub const _GLOBE: &str = "\u{F036}";
pub const _UFO: &str = "\u{F037}";
