name: Rust

on:
  pull_request: {}
  push:
    branches:
      - master

jobs:

  build:
    strategy:
      matrix:
        platform: [linux, macos, windows]
        include:
          - platform: linux
            os: ubuntu-20.04
          - platform: macos
            os: macos-10.15
          - platform: windows
            os: windows-2019
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Fetch tags
        run: git fetch --tags
      - if: matrix.platform == 'linux'
        name: Setup system dependencies (Linux)
        run: sudo apt-get install libgtk-3-dev libxcb-shape0-dev libxcb-xfixes0-dev
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          components: clippy
      - name: Cache cargo builds
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target/debug
          key: cargo-${{ matrix.platform }}-${{ hashFiles('**/Cargo.lock') }}
      - name: Run cargo build
        run: |
          cargo build --locked
      - name: Run cargo test
        run: |
          cargo test --locked
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Qglif-${{ matrix.platform }}
          path: |
            target/debug/Qglif
            target/debug/Qglif.exe

  rustfmt:
    strategy:
      fail-fast: false
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          components: rustfmt
      - name: Run rustfmt
        run: |
          git ls-files '*.rs' | xargs rustfmt --check

  cargo_bloat:
    if: false
    strategy:
      fail-fast: false
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - name: Cache cargo builds
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: cargo-bloat-${{ matrix.platform }}-${{ hashFiles('**/Cargo.lock') }}
      - name: Run cargo bloat
        uses: orf/cargo-bloat-action@v1
        with:
          token: ${{ github.token }}
